// File: __plusActivex.java
// Generated: Fri Feb 12 11:53:21 2016

// This Java source file has been automatically
// generated by EZ-JCom.

package br.com.plusoftomni.integration.domain.ocxtest;

public abstract class __plusActivex extends ezjcom.JComEventListener {

	/** Default constructor for COM-event listener object */

	public __plusActivex()
	{
		try{
			__JComEventListenerInit();
		} catch (ezjcom.JComException ex) {
			throw new RuntimeException( ex.toString());
		}
	}

	/** JNI functions used internally by EZ-JCom */
	private native boolean __JComEventListenerInit() throws ezjcom.JComException;
	static {
		System.loadLibrary( "JplusActivexProj" );
	}

}

