// File: _plusActivex.java
// Generated: Fri Feb 12 11:53:21 2016

// This Java source file has been automatically
// generated by EZ-JCom.

package br.com.plusoftomni.integration.domain.ocxtest;

/** This class corresponds to a COM interface.
  * Objects of this class are not created directly,
  * but are obtained by calling methods of other COM objects.
 */
public class _plusActivex extends ezjcom.JComObject {

	public native void login() throws ezjcom.JComException;

	public native void logout() throws ezjcom.JComException;



	// Implementation
	//

	/** Constructors for internal EZ JCom Usage only
	  * DO NOT attempt to construct this object!  It is retrieved from other objects.
	  */
	private _plusActivex() {}
	private _plusActivex( java.lang.ref.Reference ref ) {}

	private _plusActivex( ezjcom.JComObject obj ) throws ezjcom.JComException
	{
		if ( ! __JComLoad( obj, false ))
			throw new ClassCastException( "Object/interface passed does not support \"_plusActivex\"" );
	}

	/** Use this method only for creating a COM interface of type _plusActivex
	  * from another existing COM interface, when you know that it is possible.
	  */
	public static _plusActivex _ezjcomCoerceObject(ezjcom.JComObject obj) throws ezjcom.JComException { return new _plusActivex(obj);}

	/** JNI function used internally by EZ-JCom */
	native boolean __JComLoad( ezjcom.JComObject obj, boolean initial ) throws ezjcom.JComException;
	static {
		System.loadLibrary( "JplusActivexProj" );
	}

}

